protected/controllers/MainController.php
<?php
/**
 * Основной контроллер приложения
 * @author v.zubov
 */
class MainController extends Controller{
	
	/**
	 * @var array Ассоцитивный массив идентификаторов задач приложения. Задаётся в формате:
	 * 	array(
	 * 		{Цифровой идентификатор задачи}=>{Название метода данного контроллера (без префикса), отвечающего за выполнение задачи},
	 * 		...
	 * 	)
	 */
	const TASK_ACTIONS = array(
		'9482028490'=>'BackupDb',
		'4038500321'=>'BackupLog',
		'4320103383'=>'BackupAppeal',
		'2382947104'=>'BackupUser',
		'9584733545'=>'BackupExport',
		'4302285554'=>'Cleaning'
	);
	
	/**
	 * @var string Сетевой путь к папке хранения архивных данных
	 */
	const DIR_EXTERNAL_BACKUP = DIRECTORY_SEPARATOR.DIRECTORY_SEPARATOR.'192.168.60.28'.DIRECTORY_SEPARATOR.'backups'.
		DIRECTORY_SEPARATOR.'lk';
	
	/**
	 * @var string Имя файла с информацией об архивируемом обращении
	 */
	const FN_APPEAL_INFO = '_info.txt';
	
	/**
	 * @var integer Срок хранения логов, задаётся в днях
	 */
	const TIMELIMIT_LOG = 6 * 30;
	
	/**
	 * @var integer Срок хранения обращений, задаётся в днях
	 */
	const TIMELIMIT_APPEAL = 6 * 30;
	
	/**
	 * @var integer Срок хранения неактивных профилей пользователей, задаётся в днях
	 */
	const TIMELIMIT_USER = 3 * 30;
	
	/**
	 * @var integer Срок хранения файлов выгрузок данных в РГИС, задаётся в днях
	 */
	const TIMELIMIT_EXPORT = 6 * 30;
	
	/**
	 * @var integer Срок хранения временных пользовательских файлов, задаётся в секундах
	 */
	const TIMELIMIT_TEMP = 24 * 60 * 60;
	
	/**
	 * Главное действие
	 */
	public function actionIndex(){
		$model = new NewsModel('list');
		
		$this->render('index', array('model'=>$model->access ? $model : false));
	}
	
	/**
	 * Действие приватного входа
	 */
	public function actionPrivate(){
		$this->actionIndex();
	}
	
	/**
	 * Действие отображения критических ошибок приложения
	 * @throws CHttpException
	 */
	public function actionError(){
		if ($error = Yii::app()->errorHandler->error)
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else{
				if ($message = $error['message']){
					if (mb_strpos($message, 'nm_') === 0)
						Yii::app()->end();
					
					$this->schemeMode = self::SCHEME_MODE_SAFE;
				}else{
					$this->schemeMode = self::SCHEME_MODE_DISABLED;
					$message = Yii::app()->errorEvent->get($error['code'], 'description');
				}
				
				if ($message)
					Yii::app()->user->setFlash('error', $message);
				
				$this->renderText(null);
			}
		else
			throw new CHttpException(500, 'Application error');
	}
	
	/**
	 * Действие выполнения запланированных заданий приложения
	 * @param string $id Идентификатор задачи
	 */
	public function actionTask($id){
		$params_fix = array('id'=>$id, 'task'=>$id);
		
		try{
			if (Html::getUserAddr() !== Html::IP_LOCALHOST)
				throw new CHttpException(403, 'access denied');
			
			if (!array_key_exists($id, static::TASK_ACTIONS))
				throw new CHttpException(404, 'id task not found');
			
			$method_name = $params_fix['method_name'] = 'task'.($params_fix['task'] = static::TASK_ACTIONS[$id]);
			
			if (!method_exists($this, $method_name))
				throw new CHttpException(404, 'method task not found');
			
			if (!$this->$method_name())
				throw new CHttpException(500, 'error executing task');
		}catch (CException $e){
			$params_fix['msg'] = $e->getMessage();
		}
		
		$ok = !isset($e);
		
		Yii::app()->log->fix('task', $params_fix, $ok ? 'ok' : 'task', isset($params_fix['method_name']) ? 0 : false);
		
		Yii::app()->user->flashes;
		
		if (!$ok && $this->deployed && Yii::app()->email->on &&
			($user = UserModel::model()->findByPk(1)) && ($email = $user->email))
				Yii::app()->email->send($email, 'report', array('task'=>$params_fix['task']));
	}
	
	/**
	 * Действие запроса подтверждений пользователя
	 * @throws CHttpException
	 */
	public function actionConfirm(){
		if (!$confirm = Yii::app()->user->getState('confirm'))
			throw new CHttpException(500);
		
		$type = $confirm['type'];
		$model = new ConfirmModel('update');
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (Yii::app()->request->requestType !== 'POST'){
			$model->agreement = true;
			$model->secure = true;
			
			$this->renderPartial('confirm', array('model'=>$model, 'type'=>$type));
		}else{
			$model->attributes = $model->post;
			$params_fix = array('type'=>$type, 'model'=>$model->attributes);
			
			try{
				$cancel = $model->command === 'juid_confirm/cancel';
				$user = UserModel::model()->findByPk($confirm['id']);
				
				Yii::app()->log->fix('model_search', array('model'=>'user', 'id'=>$confirm['id']), $user ? 'ok' : 'model_search');
				
				$params_fix['user'] = Arrays::filterKey($user->attributes, 'password', false);
				$state = Yii::app()->conformity->get('user_state', 'name', $user->state);
				
				if (($type === WebUser::CONFIRM_TYPE_AGREEMENT && $state !== 'confirm_data') ||
					($type === WebUser::CONFIRM_TYPE_SECURE && $state !== 'working'))
						throw new CHttpException(403, 'incorrect user state');
				
				if (!$cancel)
					if ($type === WebUser::CONFIRM_TYPE_AGREEMENT){
						if (!$model->agreement)
							$cancel = true;
						else{
							$user->state = Yii::app()->conformity->get('user_state', 'code', 'working');
							$user->agreement = true;
							
							if (!$user->save(false))
								throw new CHttpException(500, 'error model save');
						}
					}elseif (!$model->secure)
						$cancel = true;
					elseif ($model->remember){
						$user->secure = false;
						
						if (!$user->save(false))
							throw new CHttpException(500, 'error model save');
					}
				
				if ($cancel)
					throw new CHttpException(500, 'cancel');
			}catch (CHttpException $e){
				$params_fix['msg'] = $e->getMessage();
			}
			
			$ok = !isset($e);
			
			if ($ok || $cancel)
				Yii::app()->user->setState('confirm', null);
			
			Yii::app()->log->fix('user_confirm', $params_fix, $ok ? 'ok' : ($e->statusCode == 404 ? 'model_search' : 'user_confirm'));
			
			if (!$ok){
				if ($params_fix['msg'] === 'cancel' && is_int(Yii::app()->user->getState('esia')))
					Yii::app()->controller->redirect(Yii::app()->controller->createUrl('esia/logout'));
				
				$this->redirect($this->createUrl(Yii::app()->defaultController));
			}else{
				$login = $type === WebUser::CONFIRM_TYPE_AGREEMENT ? Yii::app()->user->checkLogin($user) :
					Yii::app()->user->login($user);
				
				$this->redirect(Yii::app()->user->getHomeUrl($login ? $user->id : false));
			}
		}
	}
	
	/**
	 * Действие проверки доступности поддомена с сертификатом повышенной безопасности
	 * @param string $id Признак доступности
	 */
	public function actionSecure($id = false){
		if (isset($_GET['callback']))
			Yii::app()->end();
		
		if ($this->working && Html::SECURE_HOST && Yii::app()->user->isGuest && Html::secureCheck() === null &&
			((!$state = Yii::app()->user->getState('confirm')) || $state['type'] !== WebUser::CONFIRM_TYPE_SECURE))
				Yii::app()->request->cookies->add('secure', new CHttpCookie('secure', $id));
	}
	
	/**
	 * Задача по резервному копированию Базы данных приложения
	 * @return boolean Успешность выполнения
	 */
	protected function taskBackupDb(){
		try{
			$this->createAction('reserve')->run();
		}catch (CException $e){
		}
		
		return !isset($e);
	}
	
	/**
	 * Задача по резервному копированию логов приложения
	 * @return boolean Успешность выполнения
	 */
	protected function taskBackupLog(){
		Swamper::timer($tick);
		$params_fix = array('rows'=>0, 'files'=>$files = array());
		set_time_limit(0);
		
		try{
			$transaction = Yii::app()->db->beginTransaction();
			$timeout = mktime(0, 0, 0, date('n'), date('j') - static::TIMELIMIT_LOG);
			$path = $params_fix['path'] = Yii::getPathOfAlias(Log::DIR_LOG);
			$params_fix['path_archive'] = Yii::getPathOfAlias(ExportController::ALIAS_EXPORT).DIRECTORY_SEPARATOR.
				Swamper::date(false, Swamper::FORMAT_DATE_SYSTEM_WITHOUT_TIME).DIRECTORY_SEPARATOR.'log';
			$params_sql = array('condition'=>'date <= :date',
				'params'=>array(':date'=>Swamper::date($timeout, Swamper::FORMAT_DATE_SYSTEM)));
			
			if ($files_find = glob($path.DIRECTORY_SEPARATOR.'*-*-*.txt')){
				foreach ($files_find as $file_find){
					$file = pathinfo($file_find, PATHINFO_FILENAME);
					
					if (strtotime($file) <= $timeout)
						$files[] = $file;
				}
				
				$params_fix['files'] = $files;
			}
			
			if ($rows = LogModel::model()->findAll(array_merge($params_sql, array('order'=>'id')))){
				$params_fix['rows'] = count($rows);
				$day = $action = false;
				
				foreach ($rows as $row){
					if (($day_current = mb_substr($row->date, 0, 10)) !== $day){
						$action = in_array($day_current, $params_fix['files']) ? 'skip' : 'forming';
						$day = $day_current;
						
						if ($action == 'forming')
							$files[] = $params_fix['files_form'][] = $day_current;
					}
					
					if ($action == 'forming' && !Yii::app()->log->writeToFile($row->id_event, $row->id_error, $row->date,
						json_decode($row->params, true), $row->id_user))
							throw new CHttpException(500, 'error file forming');
				}
				
				if (!LogModel::model()->deleteAll($params_sql))
					throw new CHttpException(500, 'error rows delete');
			}
			
			if ($files){
				if (!is_dir($params_fix['path_archive']) && !mkdir($params_fix['path_archive'], 0777, true))
					throw new CHttpException(500, 'error create path archive');
				
				foreach ($files as $file)
					if (!rename($path.DIRECTORY_SEPARATOR.$file.'.txt', $params_fix['path_archive'].DIRECTORY_SEPARATOR.$file.'.txt'))
						throw new CHttpException(500, 'error move file');
			}
			
			$params_fix['timer'] = Swamper::timer($tick);
			$transaction->commit();
		}catch (CException $e){

protected/views/layouts/main.php
<!DOCTYPE html>

<?php
Yii::app()->getClientScript()->registerCoreScript('jquery');
Yii::app()->asset->add(array('wrap', 'content', 'popup'));

$console = $this->widget(Widget::alias('Console'), array(), true);
$flashes = $this->widget(Widget::alias('Flashes'), array(), true);
$profile = $this->getProfile();

echo Html::openTag('html');
	
	echo Html::openTag('head');
		
		echo Html::metaTag('IE=edge, chrome=1', null, 'X-UA-Compatible');
		echo Html::metaTag(null, null, null, array('charset'=>Yii::app()->charset));
		echo Html::metaTag(Yii::app()->language, 'language', null);
		echo Html::tag('title', array(), Yii::app()->setting->get('name'));
		echo Html::tag('link', array('rel'=>'shortcut icon', 'href'=>Yii::app()->homeUrl.'icon.ico'));
		
	echo Html::closeTag('head');
	
	echo Html::openTag('body');
		
		echo $console;
		
		echo Html::openTag('header');
			
			echo Html::openTag('div', array('id'=>'headline'));
				
				echo Html::openTag('div', array('class'=>'limiter'));
					
					echo Html::openTag('a', array('class'=>'logo', 'href'=>'/'));
						echo Html::openTag('div', array('class'=>'logo-frame'));
							echo Html::tag('div', array('class'=>'logo-title'), Yii::app()->setting->get('name'));
						echo Html::closeTag('div');
					echo Html::closeTag('a');
					
					echo $profile;
					
				echo Html::closeTag('div');
				
			echo Html::closeTag('div');
			
			echo Html::openTag('div', array('id'=>'scheme-main'));
				
				echo Html::tag('div', array('class'=>'limiter'), Yii::app()->scheme->render('main', true));
				
			echo Html::closeTag('div');
			
			Yii::app()->scheme->render('chain');
			
		echo Html::closeTag('header');
		
		echo Html::openTag('div', array('id'=>'base', 'class'=>'limiter'));
			
			Yii::app()->scheme->render('lateral');
			Yii::app()->scheme->render('stack');
			Yii::app()->scheme->render('title');
			
			echo Html::openTag('div', Html::forming(array(
				'id'=>'content',
				'content-offset'=>$offset = Yii::app()->scheme->contentOffset,
				'centering'=>!$offset && Yii::app()->controller->route !== 'main/index'
			)));

					echo $flashes;
					echo $content;
					
			echo Html::closeTag('div');
			
		echo Html::closeTag('div');
		
		echo Html::openTag('footer');
			echo Html::openTag('div', array('class'=>'limiter'));
				echo Html::tag('div', array('class'=>'left'), '');
				
				echo Html::openTag('div', array('class'=>'right'));
					if ($this->working){
						echo Html::openTag('div', array('class'=>'statistics'));
							if (Yii::app()->setting->get('gui', 'counter_li'))
								echo Html::tag('a', array('class'=>'liveinternet', 'target'=>'_blank', 'rel'=>'nofollow',
									'href'=>'//www.liveinternet.ru/click'), Html::tag('img', array('border'=>'0', 'width'=>'88', 'height'=>'31',
									'title'=>'LiveInternet: показано число просмотров за 24 часа, посетителей за 24 часа и за сегодня', 'alt'=>'')));
							
							if (Yii::app()->setting->get('gui', 'counter_ym'))
								echo Html::tag('a', array('class'=>'yandexmetrika', 'target'=>'_blank', 'rel'=>'nofollow',
									'href'=>'https://metrika.yandex.ru/stat/?id=43649619&amp;from=informer'),
									Html::tag('img', array('border'=>'0', 'width'=>'88', 'height'=>'31',
									'src'=>'https://informer.yandex.ru/informer/43649619/3_0_FFFFFFFF_EFEFEFFF_0_pageviews', 'alt'=>'Яндекс.Метрика',
									'title'=>'Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)',
									'class'=>'ym-advanced-informer', 'data-cid'=>'43649619', 'data-lang'=>'ru'
								)));
						echo Html::closeTag('div');
					}
				echo Html::closeTag('div');
			echo Html::closeTag('div');
		echo Html::closeTag('footer');
		
	echo Html::closeTag('body');
	
echo Html::closeTag('html');

if ($this->working && Html::SECURE_HOST && Yii::app()->user->isGuest && Html::secureCheck() === null)
	Html::registerScriptParams('secureUrl', false, false, Html::changeSecureUrl($this->createAbsoluteUrl('main/secure')));