protected/controllers/AccountController.php
<?php
/**
 * Контроллер работы с лицевыми счетами пользователя
 * @author v.zubov
 */
class AccountController extends Controller{
	
	/**
	 * @var string Шаблон строки запроса на оплату задолежнности по котловому лицевому счёту
	 * 
	 * 	land_in:
	 * 		frame - frame
	 *	 	frame_search - frame with links
	 *
	 *	def_pay_type:
	 *		card - банковская карта
	 *		yd - яндекс деньги
	 *		sms - с баланса смс
	 *		wallet - кошелек ЦК
	 *
	 *	hide_choose_pay_type:
	 *		true - hide choose payment type panel
	 *		false
	 *
	 *	hide_extra:
	 *		true - hide right panel
	 *		false
	 */
	const PATTERN_PAYMENT_URL = 'https://ckassa.ru/payment/?land_in=frame&hide_extra=true&def_pay_type=%s&'.
		'hide_choose_pay_type=true#!search_provider/pt_search/%s/pay&amount=%s&Л/СЧЕТ=%s&ФИО=%s';
	
	/**
	 * @var array Ассоциативный массив кодов оплаты в формате {Код вида лицевого счёта}=>{Код оплаты}
	 */
	const PAYMENT_CODE = array(1=>'100-11042-1', 2=>'100-11042-2');
	
	/**
	 * @var array Ассоциативный массив коммиссионных отчислений в формате
	 * 	array(
	 * 		{Символьный идентификатор типа оплаты}=>array(
	 * 			{Цифровой идентификатор типа ЛС}=>array(
	 * 				{Цифровой идентификатор вида ЛС}=>{Процент коммиссионного сбора},
	 * 				...
	 * 			),
	 * 			...
	 *		),
	 * 		...
	 * 	)
	 */
	const PAYMENT_COMMISSION = array(
		'card'=>array(2=>array(1=>1.5, 2=>1.5)),
		'yd'=>array(2=>array(1=>6, 2=>5.8)),
		'sms'=>array(2=>array(1=>1.5, 2=>1.5))
	);
	
	/**
	 * @var string Путь к папке с квитанциями
	 */
	const PATH_RECEIPT = 'C:/inetpub/receipts/';
	
	/**
	 * Действие просмотра баланса лицевых счетов пользователя
	 */
	public function actionIndex(){
		$model = new AccountModel('list');
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (!Yii::app()->request->isAjaxRequest){
			$filter_id = array();
			
			if ($accounts = Yii::app()->user->accounts){
				$counters = Yii::app()->user->counters;
				
				foreach ($accounts as $bss_role=>$accounts_role)
					foreach ($accounts_role as $id_account=>$account)
						if (!Arrays::pop($counters, "$bss_role.$id_account") && ($id_conjugation = Arrays::pop($account, 'id_conjugation')))
							$filter_id[] = $id_conjugation;
			}
			
			$this->render('index', array('model'=>$model, 'filter_id'=>$filter_id));
		}else
			$this->renderPartial('indexGrid', array('model'=>$model));
	}
	
	/**
	 * Действие просмотра операций по лицевому счёту пользователя
	 * @param boolean|string $id Идентификатор сопряжения или false. По умолчанию равно false. Если равно false, будет выбран
	 * первый идентификатор из доступных
	 */
	public function actionOperation($id = false){
		$model = new AccountOperationModel('list');
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (!Yii::app()->request->isAjaxRequest){
			$id_accounts = array();
			
			if (!$accounts = Yii::app()->user->accounts)
				throw new CHttpException(500);
			
			$roles_component = Yii::app()->user->rolesComponent;
			
			foreach ($accounts as $bss_role=>$accounts_role){
				$component = Arrays::pop($roles_component, $bss_role);
				
				foreach ($accounts_role as $id_account=>$account)
					$id_accounts[$account['id_conjugation']] = array('account'=>$account['id'], 'description'=>$id_account.' - '.
						Yii::app()->conformity->get('account_type', 'description', $component).' - '.Swamper::address($account, true),
						'component'=>$component);
			}
			
			if (!$id_accounts)
				throw new CHttpException(500);
			
			if (!isset($id_accounts[$id]))
				$id = reset(array_keys($id_accounts));
			
			Yii::app()->user->setState(WebUser::PREFIX_SET.'id_accounts', $id_accounts);
			$this->render('operation', array('model'=>$model, 'id_accounts'=>Arrays::focussing($id_accounts), 'id'=>$id));
		}else
			$this->renderPartial('operationGrid', array('model'=>$model));
	}
	
	/**
	 * Действие выбора способа оплаты по лицевому счёту пользователя
	 * @param boolean|string $id Идентификатор сопряжения или false. По умолчанию равно false. Если равно false, будет выбран
	 * первый идентификатор из доступных
	 */
	public function actionPayment($id = false){
		$model = new AccountPaymentModel;
		
		if (!$model->access ||
			(!$code_types = Arrays::select($model->accessValues['type'], 'name', false, false, 'update', 'access')))
				throw new CHttpException(500);
		
		if (!$model->post){
			if (!$accounts = Yii::app()->user->accounts)
				throw new CHttpException(500);
			
			$account_info = $account_repair = array();
			$roles_component = Yii::app()->user->rolesComponent;
			
			foreach ($accounts as $bss_role=>$accounts_role){
				$component = Arrays::pop($roles_component, $bss_role);
				
				foreach ($accounts_role as $id_account=>$account){
					$account_info[$account['id_conjugation']] = array(
						'account'=>$account['id'],
						'description'=>$id_account.' - '.Yii::app()->conformity->get('account_type', 'description', $component).' - '.
							Swamper::address($account, true),
						'type'=>Arrays::pop($account, 'type'),
						'kind'=>Arrays::pop($account, 'kind'),
						'bank'=>Arrays::pop($account, 'bank'),
						'sum'=>$sum = $account['balance'] < 0 ? -$account['balance'] : 0,
						'recipient'=>Arrays::pop($account, 'recipient'),
						'inn'=>Arrays::pop($account, 'inn'),
						'kpp'=>Arrays::pop($account, 'kpp'),
						'bik'=>Arrays::pop($account, 'bik'),
						'bank_account'=>Arrays::pop($account, 'bank_account'),
						'corr_account'=>Arrays::pop($account, 'corr_account')
					);
					
					/* if ($component == 'bss2')
						$account_repair[] = $account['id_conjugation']; */
				}
			}
			
			if (!$account_info)
				throw new CHttpException(500);
			
// 			Yii::app()->user->setState(WebUser::PREFIX_SET.'account_info', $account_info);
			
			if (!isset($account_info[$id]))
				$id = reset(array_keys($account_info));
			
			$model->id = $id;
			$model->type = reset($code_types);
			$model->sum = $account_info[$id]['sum'];
		}else{
			/* if (!$account_info = Yii::app()->user->getState(WebUser::PREFIX_SET.'account_info'))
				throw new CHttpException(500);
			
			$model->attributes = $params_fix = $model->post;
			
			try{
				if (!isset($account_info[$model->id]))
					$model->id = $params_fix['correct_id'] = reset($account_info);
				
				$id = $model->id;
				
				if (!$model->validate()){
					$params_fix['errors'] = $model->errors;
					
					if (isset($params_fix['errors']['sum']))
						$model->sum = $params_fix['correct_sum'] = $account_info[$id]['sum'];
					
					if (isset($params_fix['errors']['type']))
						$model->type = $params_fix['correct_type'] = reset($code_types);
				}
				
				if (!in_array($accounts[$id]['type'], array_keys(static::PAYMENT_CODE)))
					throw new CHttpException(500, 'error type');
			}catch (CException $e){
				$params_fix['msg'] = $e->getMessage();
			}
			
			$ok = !isset($e);
			
			Yii::app()->log->fix('account_payment', $params_fix, $ok ? 'ok' : 'account_payment');
			
			if ($ok){
				$url = sprintf(static::PATTERN_PAYMENT_URL, static::PAYMENT_CODE[$accounts[$id]['type']],
					(float)$model->sum * 100, $account_info[$model->id]['account']);
				$this->redirect($url);
			} */
		}
		
		$this->render('payment', array(
			'model'=>$model,
			'account_info'=>$account_info,
			'id'=>$id,
			'print_url'=>$this->createUrl('account/receipt'),
			'bilsys_url'=>static::PATTERN_PAYMENT_URL,
			'payment_code'=>static::PAYMENT_CODE,
			'payment_commission'=>static::PAYMENT_COMMISSION,
			'payer'=>Strings::userName(Yii::app()->user->model, Strings::FORMAT_USER_NAME_FULL)
		));
	}
	
	/**
	 * Действие просмотра квитанции на оплату по данному лицевому счёту
	 * @param string $id Идентификатор сопряжения
	 * @param boolean|integer $file Код типа запроса файла квитанции. По умолчанию равно false. Если равно 0, вернётся файл для
	 * скачивания. Если равно 1, вернётся файл для встраивания в страницу. Если равно 2, файл будет отправлен на почту
	 * @throws CHttpException
	 */
	public function actionReceipt($id, $file = false){
		$params_fix = array('id_conjugation'=>$id, 'file'=>$file !== false, 'embed'=>$file);
		
		try{
			if (!$id)
				throw new CHttpException(500, 'id_conjugation empty');
			
			if (!$accounts = Yii::app()->user->accounts)
				throw new CHttpException(500, 'list accounts empty');
			
			foreach ($accounts as $bss_role=>$accounts_role)
				foreach ($accounts_role as $account)
					if ($account['id_conjugation'] == $id){
						$params_fix['id_account'] = $id_account = $account['id'];
						break 2;
					}
			
			if (empty($id_account))
				throw new CHttpException(403, 'account access denied');
			
			$params_fix['path'] = $path = static::PATH_RECEIPT.mb_substr($id_account, 0, 5).DIRECTORY_SEPARATOR.
				($file_name = $id_account.'.pdf');
			
			if (!is_file($path))
				throw new CHttpException(404, 'file not found');
		}catch (CHttpException $e){
			$params_fix['msg'] = $e->getMessage();
		}
		
		$ok = !isset($e);
		
		Yii::app()->log->fix('receipt', $params_fix, $ok ? 'ok' : ($e->statusCode == 403 ?
			($params_fix['embed'] ? 'nm_access' : 'receipt_access') : ($e->statusCode == 404 ?
			($params_fix['embed'] ? 'nm_not_found' : 'receipt_not_found') : ($params_fix['embed'] ? 'nm_application' : 'receipt'))));
		
		if (!$params_fix['file'])
			$this->render('receipt', array('id'=>$ok ? $id : false));
		elseif (!$ok)
			throw new CHttpException(500);
		elseif ($params_fix['embed'] === '2')
			echo !Yii::app()->email->send(Yii::app()->user->model->email, 'receipt', array(
				'account'=>$account['id'],
				'address'=>$account['address'],
				'link'=>$this->createAbsoluteUrl('', array('id'=>$id)),
				'attachment'=>$path
			));
		elseif (!Files::upload($path, false, $params_fix['embed']))

protected/controllers/ArticleController.php
<?php
/**
 * Контроллер работы со статьями
 * @author v.zubov
 */
class ArticleController extends Controller{
	
	/**
	 * Действия просмотра статьи "Часто задаваемые вопросы"
	 */
	public function actionAnswer(){
		$this->render('answer');
	}
	
}

protected/views/main/confirm.php
<?php
Yii::app()->asset->add();

if ($label = Yii::app()->label->get('note_confirm_'.(($agreement = $type === WebUser::CONFIRM_TYPE_AGREEMENT) ?
	'agreement' : 'secure')))
		echo Html::tag('div', array(), sprintf($label, Yii::app()->baseUrl.'/assets/'.($agreement ?
			'user_agreement.pdf' : 'instruction_secure.pdf')));

$form = $this->beginWidget('ActiveForm', array('action'=>$this->createUrl('main/confirm'), 'command'=>true));
	
	$this->widget(Widget::alias('DataTable'), array('featureForm'=>$form, 'featureModel'=>$model, 'cells'=>array(
		TreeWidget::PARAM_ITEMS_INHERIT_DATA=>0,
		array('htmlOptions'=>array('class'=>'cell-name pl1'), 'features'=>array('checkbox')),
		array('htmlOptions'=>array('class'=>'cell-value pl1'), 'features'=>array('2.label'))
	)));
	
	$this->widget(Widget::alias('ButtonsTable'), array('params'=>array('login'=>'submit', 'cancel'=>'command')));
	
$this->endWidget();

Html::registerScriptParams('confirmToggleId', false, false, Html::activeId($model, $agreement ? 'agreement' : 'secure'));

protected/views/main/index.php
<?php
Yii::app()->asset->add();

if ($this->technicalWork && !Yii::app()->user->authorized){
	if ($note = Yii::app()->label->get('note_technical_work'))
		echo Html::tag('div', array('class'=>'note'), Html::tag('div', array(), $note));
}else{
    if (Yii::app()->user->getState('confirm'))
        $this->widget(Widget::alias('JuiDialog'), array('action'=>'confirm', 'autoOpen'=>'true', 'closing'=>false,
            'htmlOptions'=>array('id'=>'juid-confirm'), 'buttonOk'=>false, 'buttonCancel'=>false));
    elseif (Yii::app()->user->isGuest){
        echo Html::tag('div', array('class'=>'note-main'), Yii::app()->label->get('note_main_guest'));

        if ($model && ($data = $model->search()) && ($rows = $data->getData())){
            echo Html::openTag('div', array('id'=>'news-main'));
                echo Html::tag('h1', array(), Yii::app()->label->get('insert_important'));
                echo Html::link('', '#', array('class' => 'news-up'));

                echo Html::openTag('ul', array('id'=>'news-main-list'));

                foreach ($rows as $row){
                    echo Html::openTag('li');
                        echo Html::openTag('a', array('href'=>$this->createUrl('news/view', array('id'=>$row['id']))));
                            echo Html::tag('div', array('class'=>'news-title'), $row['title']);
                        echo Html::closeTag('a');
                    echo Html::closeTag('li');
                }

                echo Html::closeTag('ul');

                echo Html::link('', '#', array('class' => 'news-down'));
            echo Html::closeTag('div');
        }
    }else{
        if (Yii::app()->user->checkAccessSet('bss1_payer, bss2_payer'))
            $note = sprintf(Yii::app()->label->get('note_main_repair'), $this->createUrl('account/index'));
        elseif (Yii::app()->user->checkAccessSet('account/connection'))
            $note = sprintf(Yii::app()->label->get('note_main_citizen'), $this->createUrl('account/connection'));

        $note = Yii::app()->label->get('note_main').(!empty($note) ? Html::tag('br').Html::tag('br').$note : '');

        if ($note)
            echo Html::tag('div', array('class'=>'note'), Html::tag('div', array(), $note));
	
        echo Html::openTag('div', array('id'=>'link-list'));

            $links = array();

            if (Yii::app()->user->checkAccess('appeal/index'))
                $links['appeal'] = array('Задать вопрос.'.Html::tag('br').'Вам ответит специалист', $this->createUrl('appeal/index'));

            $links['index'] = array('Информация об утвержденных указом губернатора Пермского края предельных (максимальных) индексах '.
                'изменения размера платы, вносимой гражданами за коммунальные услуги в муниципальных образованиях',
                'https://'.Yii::app()->portal->get('link').'/norms/front', true);
            $links['answer'] = array('Ответы на часто задаваемые вопросы', $this->createUrl('article/answer'));

            foreach ($links as $name=>$params){
                echo Html::openTag('a', Html::forming(array('href'=>Arrays::pop($params, 1), $name,
                    'target'=>Arrays::pop($params, 2) ? '_blank' : false)));
                        echo Html::openTag('table');
                            echo Html::openTag('tbody');
                                echo Html::openTag('tr');
                                    echo Html::tag('td', array('class'=>'ll-icon'), '');
                                    echo Html::openTag('td', array('class'=>'ll-title'));
                                        echo Html::tag('div', array(), Arrays::pop($params, 0));
                                    echo Html::closeTag('div');
                                echo Html::closeTag('tr');
                            echo Html::closeTag('tbody');
                        echo Html::closeTag('table');
                    echo Html::closeTag('a');
            }

        echo Html::closeTag('div');

        if ($model && ($data = $model->search()) && ($rows = $data->getData())){
            echo Html::tag('h4', array(), 'Новости');

            echo Html::openTag('ul', array('id'=>'news-list'));

                foreach ($rows as $row){
                    echo Html::openTag('li');
                        echo Html::openTag('a', array('href'=>$this->createUrl('news/view', array('id'=>$row['id']))));
                            echo Html::tag('div', array('class'=>'news-title'), $row['title']);
                            echo Html::tag('div', array('class'=>'news-date'),
                                Swamper::date($row['date'], Swamper::FORMAT_DATE_USER_WITHOUT_TIME));
                            echo Html::tag('div', array('class'=>'news-text'), Strings::multilineText($row['text']));
                        echo Html::closeTag('a');
                    echo Html::closeTag('li');
                }

            echo Html::closeTag('ul');
        }
    }
}

protected/views/main/tests.php
<?php
Yii::app()->getClientScript()->registerCoreScript('jquery');
Yii::app()->asset->add();

$asserts = array();
	
	function error_state($error){
		$states = array(
			array('state'=>'ok', 'msg'=>'Успех'),
			array('state'=>'file', 'msg'=>'Файл теста не найден'),
			array('state'=>'error', 'msg'=>'Ошибка')
		);
		
		return !$error ? $states[0] : ($error === Test::ERROR_FILE ? $states[1] : $states[2]);
	}
	
echo Html::openTag('div', array('class'=>'level open'));
	$error_state = error_state($tests['error']);
	$qu_total = count($tests['tests']);
	$qu_ok = $qu_total - $tests['error'];
	
	$qu_total_tests = $qu_ok_tests = 0;
	foreach ($tests['tests'] as $test)
		if (isset($test['asserts'])){
			$qu_total_tests += $qu_total_test = count($test['asserts']);
			$qu_ok_tests += $qu_total_test - $test['error'];
		}
	
	echo Html::tag('div', array('class'=>'title'), 'Тестирование');
	
	echo Html::tag('div', array('class'=>'state '.$error_state['state']), $error_state['msg']);
	
	echo Html::tag('div', array('class'=>'quantity'), "($qu_ok_tests/$qu_total_tests - $qu_ok/$qu_total)");
	
	echo Html::tag('hr');
	
	echo Html::openTag('div', array('class'=>'childs'));
		
		foreach ($tests['tests'] as $name=>$test){
			
			echo Html::openTag('div', array('class'=>'level'.($test['error'] ? ' open' : '')));
				
				$error_state = error_state($test['error']);
				if (isset($test['asserts'])){
					$qu_total = count($test['asserts']);
					$qu_ok = $qu_total - $test['error'];
				}
				
				echo Html::tag('div', array('class'=>'title'), $name);
				
				echo Html::tag('div', array('class'=>'state '.$error_state['state']), $error_state['msg']);
				
				if (isset($test['asserts'])){
					
					echo Html::tag('div', array('class'=>'quantity'), "($qu_ok/$qu_total)");
					
					echo Html::openTag('div', array('class'=>'childs'));
						
						foreach ($test['asserts'] as $key_assert=>$assert){
							
							echo Html::openTag('div', array('class'=>'level'));
								
								$error_state = error_state($assert['error']);
								
								echo Html::tag('div', array('class'=>'title'), ++$key_assert.'. '.$assert['func']);
								
								echo Html::tag('div', array('class'=>'state '.$error_state['state']), $error_state['msg']);
								
								echo Html::tag('div', array('class'=>'line'), 'строка '.$assert['line']);
								
								echo Html::openTag('div', array('class'=>'childs'));
									
									if ($title = $assert['title'])
										echo Html::tag('div', array('class'=>'title-assert'), $title);
									
									foreach ($assert['args'] as $key=>$arg){
										
										echo Html::openTag('div', array('class'=>'arg'));
											
											Arrays::printPre($arg, false, false, $key || $title ?
												Arrays::PRINT_PRE_BORDER_TOP : Arrays::PRINT_PRE_BORDER_NONE);
											
										echo Html::closeTag('div');
									}
									
								echo Html::closeTag('div');
								
							echo Html::closeTag('div');
						}
						
					echo Html::closeTag('div');
				}
				
			echo Html::closeTag('div');
		}
		
	echo Html::closeTag('div');
	
echo Html::closeTag('div');