protected/controllers/CompensationController.php
<?php
/**
 * Контроллер работы с информацией по компенсациям, связанным с лицевыми счетами пользователя
 * @author v.zubov
 */
class CompensationController extends Controller{
	
	/**
	 * Действие просмотра общей информации по компенсациям
	 */
	public function actionIndex(){
		$model = new CompensationModel('list');
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (!Yii::app()->request->isAjaxRequest)
			$this->render('index', array('model'=>$model));
		else
			$this->renderPartial('indexGrid', array('model'=>$model));
	}
	
	/**
	 * Действие просмотра информации по выплатам по компенсации
	 */
	public function actionPayment(){
		$model = new CompensationPaymentModel('list');
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (!Yii::app()->request->isAjaxRequest){
			/* if (!$accounts = Yii::app()->user->accounts)
				throw new CHttpException(500);
			
			$id_accounts = array();
			$roles_component = Yii::app()->user->rolesComponent;
			
			foreach ($accounts as $bss_role=>$accounts_role)
				if ($bss_role == 'bss1_payer'){
					$component = Arrays::pop($roles_component, $bss_role);
					
					foreach ($accounts_role as $id_account=>$account)
						$id_accounts[$account['id']] = array('description'=>$id_account.' - '.Swamper::address($account, true),
							'component'=>$component);
				}
			
			$id = !$id_accounts ? false : reset(array_keys($id_accounts)); */
			
// 			Yii::app()->user->setState(WebUser::PREFIX_SET.'id_accounts', $id_accounts);
			$this->render('payment', array('model'=>$model/* , 'id_accounts'=>Arrays::focussing($id_accounts), 'id'=>$id */));
		}else
			$this->renderPartial('paymentGrid', array('model'=>$model));
	}
	
}

protected/views/compensation/index.php
<?php
Yii::app()->asset->add(array('gridview'));

$this->widget(Widget::alias('Flashes'),
	array('flashes'=>array('error'=>array('text'=>'error', 'html_options'=>array('class'=>'dsp-none')))));

echo Html::openTag('div', array('class'=>'container-grid-view'));
	$this->renderPartial('indexGrid', array('model'=>$model));
	echo Html::tag('div', array('class'=>'curtain-loading'), '');
echo Html::closeTag('div');

$this->widget(Widget::alias('ButtonsTable'), array('params'=>array(
	'disbursement'=>array('html_options'=>array('href'=>$this->createUrl('compensation/payment'))))));

protected/views/compensation/indexGrid.php
<?php
$items = Html::tag('div', array('class'=>'gv-table'), '{items}');

foreach ($model->allowedAttributeNames as $name)
	$columns[] = array(
		'header'=>$model->getAttributeLabel($name),
		'name'=>$name,
		'headerHtmlOptions'=>array('class'=>'nowrap'),
		'htmlOptions'=>array('class'=>'nowrap ta-center')
	);

$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'compensations-grid',
	'dataProvider'=>$model->search(),
	'ajaxType'=>'POST',
	'template'=>$items,
	'cssFile'=>false,
	'beforeAjaxUpdate'=>'gridviewBeforeAjaxUpdate',
	'afterAjaxUpdate'=>'gridviewAfterAjaxUpdate',
	'ajaxUpdateError'=>'gridviewErrorAjaxUpdate',
	'emptyText'=>Yii::app()->label->get(Yii::app()->request->isAjaxRequest ? 'wgv_empty' : 'wgv_loading'),
	'selectableRows'=>0,
	'columns'=>$columns
));

protected/views/compensation/payment.php
<?php
Yii::app()->asset->add(array('gridview'));

$this->widget(Widget::alias('Flashes'),
	array('flashes'=>array('error'=>array('text'=>'error', 'html_options'=>array('class'=>'dsp-none')))));

/* echo Html::openTag('div', array('class'=>'filter'));
	
	echo Html::openTag('div', array('class'=>'filter-item fi-not-clean'));
		echo Html::label('Лицевой счёт', Widget::PREFIX_ID.'1');
		echo Html::hiddenField('filter-payment-account', $id, array('class'=>'filter-field'));
		$this->widget(Widget::alias('DropDownList'), array(
			'data'=>$id_accounts ? $id_accounts : array('empty'=>array('access'=>'view')),
			'name'=>'filter-account',
			'value'=>$id,
			'widthInitial'=>true,
			'readonly'=>true
		));
	echo Html::closeTag('div');
	
	echo Html::openTag('div', array('class'=>'filter-buttons'));
		echo Html::link('', '#', array('class'=>'button search contur circle'));
	echo Html::closeTag('div');
	
echo Html::closeTag('div'); */

echo Html::openTag('div', array('class'=>'container-grid-view'));
	$this->renderPartial('paymentGrid', array('model'=>$model));
	echo Html::tag('div', array('class'=>'curtain-loading'), '');
echo Html::closeTag('div');

protected/views/compensation/paymentGrid.php
<?php
$data = $model->search();
$items = Html::tag('div', array('class'=>'gv-table'), '{items}');
$sizer = $data->totalItemCount > 10 ? Html::tag('div', array('class'=>'sizer'), Html::tag('p', array(), 'Показывать по ').
	Html::radioButtonList('filter-size', $data->pagination->pageSize, $model::FILTER_SIZE_VALUES,
	array('class'=>'filter-field', 'container'=>'div', 'separator'=>false,
	'template'=>Html::tag('span', array(), '{input}{label}')))) : '';
$controls = Html::tag('table', array('class'=>'gv-controls'), Html::tag('tr', array(),
	Html::tag('td', array('class'=>'gv-summary'), '{summary}').
	Html::tag('td', array('class'=>'gv-sizer'), $sizer).
	Html::tag('td', array('class'=>'gv-pager'), '{pager}')
));

foreach ($model->allowedAttributeNames as $name)
	$columns[] = array(
		'header'=>$model->getAttributeLabel($name),
		'name'=>$name,
		'type'=>'raw',
		'headerHtmlOptions'=>array('class'=>'nowrap'),
		'htmlOptions'=>Html::forming(array('nowrap'=>in_array($name, array('date', 'sum')), 'ta-center'))
	);

$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'compensation-payment-grid',
	'dataProvider'=>$data,
	'htmlOptions'=>array('class'=>'grid-view gv-wide'),
	'filterSelector'=>'input.filter-field',
	'ajaxType'=>'POST',
	'template'=>Yii::app()->request->isAjaxRequest ? ($data->itemCount > 24 ? $controls : '').$items.$controls : $items,
	'cssFile'=>false,
	'beforeAjaxUpdate'=>'gridviewBeforeAjaxUpdate',
	'afterAjaxUpdate'=>'gridviewAfterAjaxUpdate',
	'ajaxUpdateError'=>'gridviewErrorAjaxUpdate',
	'emptyText'=>Yii::app()->label->get(Yii::app()->request->isAjaxRequest ? 'wgv_empty' : 'wgv_loading'),
	'summaryText'=>'Найдено: <strong>{count}</strong>',
	'selectableRows'=>0,
	'columns'=>$columns,
	
	'pager'=>array(
		'cssFile'=>false,
		'hiddenPageCssClass'=>'dsp-none',
		'firstPageLabel'=>'',
		'prevPageLabel'=>'',
		'nextPageLabel'=>'',
		'lastPageLabel'=>'',
		'maxButtonCount'=>7,
		'header'=>''
	)
));