protected/controllers/EsiaController.php
<?php
/**
 * Контроллер работы с ЕСИА
 * @author v.zubov
 */
class EsiaController extends Controller{
	
	/**
	 * Действие авторизации пользователя через сервис ЕСИА
	 */
	public function actionLogin(){
		Yii::app()->esia->login();
	}
	
	/**
	 * Действие разавторизации пользователя, авторизованного через сервис ЕСИА
	 */
	public function actionLogout(){
		Yii::app()->esia->logout();
	}
	
}

protected/controllers/UserController.php
<?php
/**
 * Контроллер работы с пользователями
 * @author v.zubov
 */
class UserController extends Controller{
	
	/**
	 * Действия просмотра списка пользователей
	 */
	public function actionIndex(){
		$model = new UserModel('list');
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (!Yii::app()->request->isAjaxRequest)
			$this->render('index', array('model'=>$model));
		else
			$this->renderPartial('indexGrid', array('model'=>$model));
	}
	
	/**
	 * Действие разлогинивания пользователя
	 */
	public function actionLogout(){
		if (!Yii::app()->user->logout())
			throw new CHttpException(500);
	}
	
	/**
	 * Действие самостоятельной регистриции пользователя
	 * @param boolean|string Код подтверждения
	 */
	public function actionRegistration($code = false){
		/* $fn = Yii::getPathOfAlias('webroot.assets.user_agreement').'.pdf';
		
		if (is_file($fn)){
			header("Content-Type: application/force-download");
			header("Content-Type: application/octet-stream");
			header("Content-Type: application/download");
			header("Content-Disposition: attachment; filename=1.pdf");
			header("Content-Transfer-Encoding: binary");
			
			readfile($fn);
		}else
			Arrays::printPre(); */
		
		if ($code){
			$params_fix = array('code'=>$code, 'email_send'=>false);
			
			try{
				$transaction = Yii::app()->db->beginTransaction();
				
				if (!($model = Yii::app()->code->checkHash($code, 'email')) ||
					$model->state != Yii::app()->conformity->get('user_state', 'code', 'confirm_data') ||
					!Yii::app()->code->dropCode($model->code[0]->code, 'email'))
						throw new CHttpException(500);
				
				$params_fix['user'] = $model->attributes;
				$model->state = Yii::app()->conformity->get('user_state', 'code', 'working');
				$model->agreement = true;
				
				if (!$model->save(false))
					throw new CHttpException(500);
				
				if (Yii::app()->email->on){
					$email_send = !Yii::app()->email->send($model->email, 'registration', array('fio'=>Strings::userName($model,
						Strings::FORMAT_USER_NAME_INITIALS), 'login'=>$model->login, 'link'=>$this->createAbsoluteUrl('user/restore')));
					
					if ($email_send)
						$params_fix['email_send'] = true;
					else
						throw new CHttpException(500, 'error email send');
				}
				
				$transaction->commit();
			}catch (CException $e){
				$transaction->rollback();
				$params_fix['msg'] = $e->getMessage();
			}
			
			$ok = !isset($e);
			
			Yii::app()->log->fix('user_registration_confirm', $params_fix, $ok ? 'ok' : 'user_registration_confirm');
			
			if ($ok){
				if ($description = Yii::app()->label->get('info_user_registration_confirm'))
					Yii::app()->user->setFlash('ok', array('text'=>$description, 'only_flash'=>true));
				
				$this->refreshWithoutParams();
			}
			
			Yii::app()->end();
		}
		
		$this->actionUpdate();
	}
	
	/**
	 * Действие добавления нового пользователя
	 */
	public function actionCreate(){
		$this->actionUpdate();
	}
	
	/**
	 * Действие редактирования данных профиля текущего пользователя
	 */
	public function actionPupdate(){
		$this->actionUpdate();
	}
	
	/**
	 * Действие редактирования данных пользователя.
	 * Таблица возможных действий над моделью:
	 * 	controller	action				id		model_action
	 * 	----------------------------------------
	 * 	user				registration				create
	 * 	user				create							create
	 * 	user				update				+			update
	 * 	user				pupdate							update
	 * @throws CHttpException
	 */
	public function actionUpdate($id = false){
		$action = $this->action->id;
		$registration = $action == 'registration';
		$user_states = Yii::app()->conformity->get('user_state', 'code', 'name');
		
		if ($pupdate = $action == 'pupdate')
			$model = Yii::app()->user->model;
		elseif (!$id)
			$model = new UserModel;
		else{
			$model = UserModel::model()->findByPk($id);
			
			Yii::app()->log->fix('model_search', array('model'=>'user', 'id'=>$id), $model ? 'ok' : 'model_search');
		}
		
		if (!$model)
			throw new CHttpException(500);
		
		$create = $model->action == 'create';
		
		if (!$create && !empty($model->post['password']) && empty($model->post['password2']) &&
			empty($model->post['passwordcode']) && Hashing::check($model->post['password'], $model))
				$model->setPost(Arrays::filterKey($model->post, 'password', false), $model::SET_POST_MODE_EASY);
		
		$model->hidePassword();
		
		if (!$model->access)
			throw new CHttpException(500);
		
		if (!$model->post){
			if ($create){
				if ($roles_update = Arrays::select($model->accessValues['roles'], 'code', 'name', false, 'update', 'access'))
					$model->roles = array(isset($roles_update['citizen']) ? $roles_update['citizen'] :
						(isset($roles_update['organization']) ? $roles_update['organization'] : reset($roles_update)));
				
				if ($state_update = Arrays::select($model->accessValues['state'], 'code', 'name', false, 'update', 'access'))
					$model->state = array(isset($state_update['working']) ? $state_update['working'] : reset($state_update));
				
				$model->agreement = true;
			}
		}else{
			$model->attributes = $model->post;
			
			if ($model->validate()){
				$model->removeDecoration();
				$password = $model->password;
				
				try{
					$transaction = Yii::app()->db->beginTransaction();
					$confirm_data = Yii::app()->setting->get('user_registration_type') == 'confirm_data';
					
					if ($create){
						if ($registration)
							$model->state = Yii::app()->conformity->get('user_state', 'code', $confirm_data ? 'confirm_data' : 'working');
						
						$model->registration = Swamper::date(false, Swamper::FORMAT_DATE_SYSTEM);
						$model->agreement = !$confirm_data || !$registration;
						$model->secure = true;
					}elseif ((int)$model->state === $user_states['remote'])
						$model->locked = Swamper::date(false, Swamper::FORMAT_DATE_SYSTEM);
					elseif ((int)$model->state == $user_states['locked'])
						$model->locked = Swamper::date($model->locked, Swamper::FORMAT_DATE_SYSTEM);
					else
						$model->locked = null;
					
					$model->delivery = Yii::app()->conformity->get('user_delivery_type', 'code', 'email');
					$model->password = $model->accessAttributes['password'] == 'update' ?
						Hashing::encode($model->password, Hashing::key($model->login)) : $model->passwordHash;
					
					if (!$model->save(false))
						throw new CHttpException(500);
					
					if ($model->accessAttributes['roles'] == 'update'){
						$roles_prev = $model->prevValues['roles'] ?
							Yii::app()->user->getRoles(0, 'name', false, false, $model->prevValues['roles'], 'id', false) : array();
						$roles = $model->roles ? Yii::app()->user->getRoles(0, 'name', false, false, $model->roles, 'id', false) : array();
						
						foreach (array_diff($roles_prev, $roles) as $role)
							Yii::app()->user->revoke($role, $model->id);
						
						foreach (array_diff($roles, $roles_prev) as $role)
							Yii::app()->user->assign($role, $model->id);
					}
					
					if ($registration && $confirm_data && ((!$hash = Yii::app()->code->getHash($model, 'email')) ||
						Yii::app()->email->send($model->email, 'registration_confirm',
						array('link'=>$this->createAbsoluteUrl('', array('code'=>$hash['hash']))))))
							throw new CHttpException(500, 'error email send');
					
					$transaction->commit();
				}catch (CException $e){
					$transaction->rollback();
				}
				
				$ok = !isset($e);
				$model->password = $password;
				$params_fix = array('model'=>$model->getAttributes($model->classAttributeNames));
				
				if (!$ok)
					$params_fix['msg'] = $e->getMessage();
				elseif (!empty($hash))
					$params_fix['code'] = $hash['code'];
				
				Yii::app()->log->fix('user_'.$action, $params_fix, $ok ? 'ok' : 'user_'.$action);
				
				if ($ok){
					if ($create)
						if ($registration){
							if ($confirm_data){
								if ($description = Yii::app()->label->get('info_user_registration'))
									Yii::app()->user->setFlash('ok', array('text'=>$description, 'only_flash'=>true));
							}else{
								if (Yii::app()->email->on)
									Yii::app()->email->send($model->email, 'registration',
										array('fio'=>Strings::userName($model, Strings::FORMAT_USER_NAME_INITIALS), 'login'=>$model->login,
										'link'=>$this->createAbsoluteUrl('user/restore')));
								
								$this->redirect($this->createUrl(Yii::app()->defaultController));
							}
						}else
							$this->redirectAccessible(array(
								'user/view'=>array('id'=>$model->id),
								'user/update'=>array('id'=>$model->id),
								'user/index'
							));
					elseif ($pupdate && $model->state !== Yii::app()->conformity->get('user_state', 'code', 'working'))
						Yii::app()->user->logout();
					
					$this->refreshWithoutParams(true);
				}
			}
		}
		
		if ((int)$model->state === $user_states['remote'])
			$model->delete = $model->locked;
		
		$model->locked = Swamper::date((int)$model->state === $user_states['locked'] && $model->locked ?
			$model->locked : time() + 3600);
		$model->post = false;
		
		$this->render('update', array('action'=>$action, 'model'=>$model, 'user_states'=>$user_states));
	}
	
	/**
	 * Действие просмотра данных профиля текущего пользователя
	 */
	public function actionPview(){
		$this->actionView();
	}
	
	/**
	 * Действие просмотра данных пользователя
	 * Таблица возможных действий над моделью:
	 * 	controller	action				id		model_action
	 * 	----------------------------------------
	 * 	user				view					+			view
	 * 	user				pview								view
	 * @param integer $id Идентификатор обращения
	 * @throws CHttpException
	 */
	public function actionView($id = false){
		if ($this->action->id == 'pview')
			$model = Yii::app()->user->getModel('view');
		else{
			if ($model = UserModel::model()->findByPk($id))

protected/views/user/code.php
<?php
Yii::app()->asset->add();

$form = Yii::app()->controller->beginWidget('ActiveForm', array(
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
		'afterValidate'=>'js:function(form, data, hasError){
				console.log(hasError);
				console.log(data);
// 				if (!hasError)
// 					return false;
// 					return true;
			}'
	)
));
	
	Yii::app()->controller->widget(Widget::alias('DataTable'), array('featureForm'=>$form, 'featureModel'=>$model,
		'attrException'=>array('captchacode'),
		'attributes'=>array(
			'emailcode, phonecode'=>array('attrHidden'=>!Arrays::pop($params, 'emailcode.visible'),
				'features'=>array('2.text'=>array('htmlOptions'=>array('autocomplete'=>'off')),
				'2.widget'=>array('widgetName'=>'Code'), '2.error')),
			'phonecode'=>array('attrHidden'=>!Arrays::pop($params, 'phonecode.visible'))
		)
	));
	
	Yii::app()->controller->widget(Widget::alias('ButtonsTable'), array('model'=>$model, 'params'=>array('ok', 'cancel')));
	
Yii::app()->controller->endWidget();

protected/views/user/index.php
<?php
Yii::app()->asset->add(array('gridview'));

$this->widget(Widget::alias('Flashes'),
	array('flashes'=>array('error'=>array('text'=>'error', 'html_options'=>array('class'=>'dsp-none')))));

echo Html::openTag('div', array('class'=>'filter'));
	
	echo Html::openTag('div', array('class'=>'filter-item'));
		echo Html::label('ФИО', 'filter-user-title');
		echo Html::textField('filter-user-title', '', array('class'=>'filter-field'));
	echo Html::closeTag('div');
	
	echo Html::openTag('div', array('class'=>'filter-item'));
		echo Html::label('Группа', Widget::PREFIX_ID.'1');
		echo Html::hiddenField('filter-user-roles', '', array('class'=>'filter-field'));
		$this->widget(Widget::alias('DropDownList'), array(
			'data'=>Yii::app()->user->getRoles(0, 'description', 'id', 'guest'),
			'widthMin'=>250,
			'widthMax'=>250,
			'multiple'=>true,
			'readonly'=>true,
			'itemAllEnabled'=>true
		));
	echo Html::closeTag('div');
	
	echo Html::openTag('div', array('class'=>'filter-item'));
		echo Html::label('Статус', Widget::PREFIX_ID.'2');
		echo Html::hiddenField('filter-user-state', '', array('class'=>'filter-field'));
		$this->widget(Widget::alias('DropDownList'), array(
			'data'=>Yii::app()->conformity->get('user_state', 'description', 'code', 'confirm_admin'),
			'widthMin'=>230,
			'widthMax'=>230,
			'multiple'=>true,
			'readonly'=>true,
			'itemAllEnabled'=>true
		));
	echo Html::closeTag('div');
	
	echo Html::openTag('div', array('class'=>'filter-buttons'));
		echo Html::link('', '#', array('class'=>'button search contur circle'));
		echo Html::link('', '#', array('class'=>'button clear contur circle'));
	echo Html::closeTag('div');
	
echo Html::closeTag('div');

echo Html::openTag('div', array('class'=>'container-grid-view'));
	$this->renderPartial('indexGrid', array('model'=>$model));
	echo Html::tag('div', array('class'=>'curtain-loading'), '');
echo Html::closeTag('div');

$params_bt = array('view'=>array('html_options'=>array('class'=>Html::CLASS_NEED_ID.' disabled', 'tabindex'=>-1)));

if (Yii::app()->user->checkAccess('developer') || Yii::app()->user->checkAccess('administrator')){
	$params_bt = array('create') + $params_bt;
	$params_bt['update'] = array('html_options'=>array('class'=>Html::CLASS_NEED_ID.' disabled', 'tabindex'=>-1));
	$params_bt['delete'] = array('html_options'=>array('class'=>Html::CLASS_NEED_ID.' disabled '.
		Html::PREFIX_BUTTON_STARTER_JD.'-juid-confirm', 'tabindex'=>-1));
}

$this->widget(Widget::alias('ButtonsTable'), array('params'=>$params_bt));

$this->widget(Widget::alias('JuiDialog'), array('view'=>'confirm',
	'htmlOptions'=>array('id'=>'juid-confirm'), 'buttonOk'=>'yes', 'buttonCancel'=>'no'));

protected/views/user/indexGrid.php
<?php
$data = $model->search();
$items = Html::tag('div', array('class'=>'gv-table'), '{items}');
$sizer = $data->totalItemCount > 10 ? Html::tag('div', array('class'=>'sizer'), Html::tag('p', array(), 'Показывать по ').
	Html::radioButtonList('filter-size', $data->pagination->pageSize, $model::FILTER_SIZE_VALUES,
	array('class'=>'filter-field', 'container'=>'div', 'separator'=>false,
	'template'=>Html::tag('span', array(), '{input}{label}')))) : '';
$controls = Html::tag('table', array('class'=>'gv-controls'), Html::tag('tr', array(),
	Html::tag('td', array('class'=>'gv-summary'), '{summary}').
	Html::tag('td', array('class'=>'gv-sizer'), $sizer).
	Html::tag('td', array('class'=>'gv-pager'), '{pager}')
));

if (($rows = $data->getData()) && ($roles_list = Yii::app()->user->rolesList) &&
	($developer = Arrays::pop($roles_list, 'developer.description')) &&
	($administrator = Arrays::pop($roles_list, 'administrator.description'))){
		$this_developer = Yii::app()->user->checkAccess('developer');
		$this_administrator = Yii::app()->user->checkAccess('administrator');
		$filter_id_delete = $filter_id_update = array();
		$state_remote = Yii::app()->conformity->get('user_state', 'description', 'remote');
		
		foreach ($rows as $row){
			list($id, $roles, $state) = Arrays::pop($row, 'id, roles, state');
			
			if ($roles){
				$roles = Strings::devisionWords($roles);
				$is_developer = in_array($developer, $roles);
				$is_administrator = in_array($administrator, $roles);
				
				if ($this_developer && $is_developer)
					$filter_id_delete[] = $id;
				elseif ($this_administrator)
					if (($is_developer || $is_administrator) && $id != Yii::app()->user->id)
						$filter_id_update[] = $filter_id_delete[] = $id;
				
				if ($state == $state_remote)
					$filter_id_delete[] = $id;
			}
		}
		
		$filter_id = json_encode(array('update'=>$filter_id_update, 'delete'=>$filter_id_delete));
	}

$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'users-grid',
	'dataProvider'=>$data,
	'filterSelector'=>'input.filter-field',
	'ajaxType'=>'POST',
	'template'=>(Yii::app()->request->isAjaxRequest ? ($data->itemCount > 24 ? $controls : '').$items.$controls : $items).
		(!empty($filter_id) ? Html::tag('div', array('id'=>Html::ID_FILTER_ID), $filter_id) : ''),
	'cssFile'=>false,
	'beforeAjaxUpdate'=>'gridviewBeforeAjaxUpdate',
	'afterAjaxUpdate'=>'gridviewAfterAjaxUpdate',
	'ajaxUpdateError'=>'gridviewErrorAjaxUpdate',
	'emptyText'=>Yii::app()->label->get(Yii::app()->request->isAjaxRequest ? 'wgv_empty' : 'wgv_loading'),
	'summaryText'=>'Найдено: <strong>{count}</strong>',
	
	'columns'=>array(
		array(
			'header'=>'ФИО / Название',
			'name'=>'title'
		),
		array(
			'name'=>'roles'
		),
		array(
			'name'=>'state',
			'htmlOptions'=>array('class'=>'nowrap ta-center')
		),
		array(
			'name'=>'registration',
			'htmlOptions'=>array('class'=>'nowrap ta-center')
		)
	),
	
	'pager'=>array(
		'cssFile'=>false,
		'hiddenPageCssClass'=>'dsp-none',
		'firstPageLabel'=>'',
		'prevPageLabel'=>'',
		'nextPageLabel'=>'',
		'lastPageLabel'=>'',
		'maxButtonCount'=>7,
		'header'=>''
	)
));

protected/views/user/login.php
<?php
Yii::app()->asset->add(array('button', 'flash_panel', 'input'));

$guest = Yii::app()->user->isGuest;
$login = Yii::app()->user->checkAccess('*/login');

if (!Yii::app()->user->getState('confirm')){
    echo Html::openTag('div', array('id'=>'profile', 'class'=>$login ? 'profile-login' : ''));
        if ($login){
            if ($this->route === 'main/index') {
                echo Html::link(Yii::app()->label->get('button_auth'), '#', Html::forming(
                    array('button-main', Html::PREFIX_BUTTON_STARTER_FP.'-profile', 'fix, '.Html::CLASS_BUTTON_FP_POPUP=>$guest)));

                echo Html::openTag('div', array('class'=>'flash-panel', 'id'=>Html::PREFIX_ID_FLASH_PANEL.'profile'));
                    $scheme_item = Yii::app()->scheme->getSchemeItem('*/login');

                    echo Html::tag('h2', array('class'=>'mb2'), $scheme_item['title']);

                    $form = $this->beginWidget('ActiveForm', array('id'=>'profile'));

                        $this->widget(Widget::alias('DataTable'), array('featureForm'=>$form, 'featureModel'=>$model,
                            'htmlOptions'=>array('class'=>'unrequired'),
                            'attributes'=>array(
                                'login'=>array('features'=>array('2.text'=>array('htmlOptions'=>array('autocomplete'=>'off')), '2.error')),
                                'password'=>array('features'=>array('2.password'=>array('htmlOptions'=>array('autocomplete'=>'off')), '2.error'))
                            )
                        ));

                        if (Yii::app()->esia->on)
                            $params_bt['esia'] = array('html_options'=>array('href'=>$this->createUrl('esia/login')));

                        $params_bt['login'] = array('type'=>'ajax_submit', 'ajax_params'=>array('url'=>$scheme_item['_link'],
                            'dataType'=>'json', 'beforeSend'=>'loginBeforeSend', 'success'=>'loginSuccess', 'error'=>'loginError',
                            'context'=>'js:$(this)'));


                        $this->widget(Widget::alias('ButtonsTable'), array('form'=>$form, 'model'=>$model, 'mergeParams'=>false,
                            'params'=>$params_bt, 'horizontalAlign'=>'right'));

                        if (Yii::app()->email->on)
                            echo Html::link(Yii::app()->label->get('user_restore'), $this->createUrl('user/restore'),
                                array('class'=>'user-restore'));

                    $this->endWidget();

                    echo Html::tag('div', array('class'=>'curtain-loading'), '');
                echo Html::closeTag('div');
            }
        }else{
            echo Html::openTag('div', array('class'=>'profile-info'));

                echo Html::tag('div', array('class'=>'hello'), sprintf(Yii::app()->label->get('insert_hello'),
                    Strings::userName(Yii::app()->user->model, Strings::FORMAT_USER_NAME_INITIALS)));

                $scheme_item = Yii::app()->scheme->getSchemeItem('*/login');
                echo Html::tag('a', array('class'=>'link-profile', 'href'=>$this->createUrl('profile/view')),
                    Html::tag('span', array(), Yii::app()->label->get('insert_profile')));
                echo Html::tag('a', array('class'=>'link-logout', 'href'=>$this->createUrl('user/logout')),
                    Html::tag('span', array(), Yii::app()->label->get('insert_logout')));
    // 			echo Html::link(Yii::app()->label->get('insert_logout'), $this->createUrl('user/logout'), array('class'=>'link-logout'));
                /* echo Html::tag('h3', array(), Strings::userName(Yii::app()->user->model));

                echo Html::element(array('type'=>'value', 'model'=>Yii::app()->user->model, 'name'=>'roles',
                    'htmlOptions'=>array('class'=>'value-list value-big'))); */

            echo Html::closeTag('div');

            /* $this->widget(Widget::alias('ButtonsTable'), array('params'=>array('logout'=>array('html_options'=>array(
                'href'=>$this->createUrl('user/logout')))), 'mergeParams'=>false, 'class'=>'mono', 'horizontalAlign'=>'right')); */
        }
    echo Html::closeTag('div');
}

protected/views/user/restore.php
<?php
Yii::app()->asset->add(array('button', 'input'));

if (!$code && ($note = Yii::app()->label->get('note_restore')))
	echo Html::tag('div', array('class'=>'note'), Html::tag('div', array(), $note));

$form = $this->beginWidget('ActiveForm');
	
	$this->widget(Widget::alias('DataTable'), array('featureForm'=>$form, 'featureModel'=>$model,
		TreeWidget::PARAM_ATTRIBUTES_FULL=>false,
		'attributes'=>!$code ?
			array(
				'restore'=>array('features'=>array()),//!
				'captchacode'=>array('features'=>array(
					'2.text'=>array('htmlOptions'=>array('autocomplete'=>'off', 'style'=>'width: 306px')),
					'2.widget'=>array('widgetName'=>'Captcha'),
					'2.error'
				))
			) : array(
				'login'=>array('features'=>array('1.label'=>array('htmlOptions'=>array('disabled'=>false)),
					'2.value'=>array('htmlOptions'=>array('class'=>'value-wide value-update')))),
				'password'=>array('features'=>array(
					'2.password'=>array('htmlOptions'=>array('autocomplete'=>'off', 'style'=>'width: 405px', 'readonly'=>'readonly')),
					'2.widget'=>array('widgetName'=>'DifficultyMeter'),
					'2.error'
				)),
				'password2'=>array('features'=>array(
					'2.password'=>array('htmlOptions'=>array('autocomplete'=>'off', 'style'=>'width: 405px', 'readonly'=>'readonly')),
					'2.error'
				))
			)
	));
	
	$this->widget(Widget::alias('ButtonsTable'), array('form'=>$form, 'model'=>$model));
	
$this->endWidget();

protected/views/user/setting.php
<?php
Yii::app()->asset->add(array('button'));

$form = $this->beginWidget('ActiveForm', array('command'=>true/* , 'htmlOptions'=>array('class'=>'w100') */));
	
	$this->widget(Widget::alias('DataTable'), array('featureForm'=>$form, 'featureModel'=>$model,
		'htmlOptions'=>array('class'=>'unrequired'), TreeWidget::PARAM_ATTRIBUTES_FULL=>false,
		'attributes'=>array(
			'delivery'=>array('features'=>array(
				'2.widget'=>array('widgetName'=>'DropDownList', 'widgetParams'=>array('widthMin'=>300, 'widthMax'=>300,
					'readonly'=>true)),
				'2.error_static'
			)),
			'esia'=>array('features'=>array(
				'1.label'=>array('htmlOptions'=>array('disabled'=>false)),
				'2.value'=>array('featureModel'=>false, 'featureValue'=>Yii::app()->label->get('insert_is'.
					($model->esia ? '' : 'no')), 'htmlOptions'=>array('class'=>'value-big value-wide'))
			))
		)));
	
	$this->widget(Widget::alias('ButtonsTable'), array('form'=>$form, 'model'=>$model, 'mergeParams'=>false, 'params'=>array(
		'save', 'esiadone'=>array('html_options'=>array('class'=>Html::PREFIX_BUTTON_STARTER_JD.'-juid-confirm')))));
	
$this->endWidget();

if ($model->esia)
	$this->widget(Widget::alias('JuiDialog'), array('view'=>'confirm', 'htmlOptions'=>array('id'=>'juid-confirm'),
		'buttonOk'=>'yes', 'buttonCancel'=>'no', 'params'=>array('label'=>'user_esia')));

protected/views/user/view.php
<?php
Yii::app()->asset->add(array('button'));

$roles = Yii::app()->user->getRoles($model->id, 'name');

$this->widget(Widget::alias('DataTable'), array('featureModel'=>$model, 'htmlOptions'=>array('class'=>'unrequired'),
	'attrSeparation'=>array(
		array('roles, state, registration, locked, delete'),
		array('login'),
		array('surname, name, patronymic, title', 'powers'),
		array('address, email, phone')
	),
	'attributes'=>array(
		'locked'=>array('attrHidden'=>(int)$model->state !== Yii::app()->conformity->get('user_state', 'code', 'locked')),
		'delete'=>array('attrHidden'=>(int)$model->state !== Yii::app()->conformity->get('user_state', 'code', 'remote')),
		'surname, name, patronymic'=>array('attrHidden'=>!in_array('citizen', $roles)),
		'title'=>array('attrHidden'=>!in_array('organization', $roles)),
		'powers'=>array('attrHidden'=>!in_array('organization', $roles) || !$model->powers)
	),
	'features'=>array(TreeWidget::PARAM_ITEMS_PRIORITY=>2,
		'1.label'=>array('htmlOptions'=>array('disabled'=>false)),
		'2.value'=>array('htmlOptions'=>array('class'=>'value-big value-wide'))
	)
));

$this->widget(Widget::alias('ButtonsTable'), array('model'=>$model,
	'params'=>array('delete'=>array('html_options'=>array('class'=>Html::PREFIX_BUTTON_STARTER_JD.'-juid-confirm')))));

$this->widget(Widget::alias('JuiDialog'), array('view'=>'confirm',
	'htmlOptions'=>array('id'=>'juid-confirm'), 'buttonOk'=>'yes', 'buttonCancel'=>'no'));